sudo: false
language: android

android:
  components:
    - build-tools-27.0.1        

jdk:
  - oraclejdk8

script: ./gradlew build

cache:
  directories:
    - "$HOME/.gradle/caches"

branches:
  only:
    - master
