sudo: false
language: android

android:
  components:
    - tools
    - build-tools-27.0.1
    - android-22

jdk:
  - oraclejdk8

script: ./gradlew build --stacktrace -i

cache:
  directories:
    - "$HOME/.gradle/caches"

branches:
  only:
    - master
